name: cm4ai-qcomm

channels:
  - defaults

dependencies:
  - python=3.9
  - pip

  - pip:
    - azure-cli
    - dwave-hybrid==0.6.10
    - dwave-system==1.21.0
    - matplotlib
    - networkx
    - pandas
    - azure-ai-ml
    - azure-core
    - azureml-mlflow
    - azureml-core
    - ray[data,train,tune,serve]
    - scikit-learn